language: python


python:
  - "3.5.2"
  
sudo: false

# command to install dependencies
install: 
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
# command to run tests
script: python manage.py test

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
